name: Web testing CI
on:
  push:
  # Only trigger if files in this path changed
    paths:
    - 'web-testing-2022/**'
    - '.github/workflows/web2022.yml'
    # Don't run on Markdown changes
    - '!**.md'
    branches: [ master ]
  pull_request:
  # Only trigger if files in this path changed
    paths:
    - 'web-testing-2022/**'
    - '.github/workflows/web2022.yml'
    # Don't run on Markdown changes
    - '!**.md'
    branches: [ master ]
jobs:
  happo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run happo-ci-github-actions
        env:
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
