name: Web testing 2022
on:
  push:
  # Only trigger if files in this path changed
    paths:
    - 'web-testing-2022/**'
    - '.github/workflows/web2022.yml'
    # Don't run on Markdown changes
    - '!**.md'
    branches: [ master ]
  pull_request:
  # Only trigger if files in this path changed
    paths:
    - 'web-testing-2022/**'
    - '.github/workflows/web2022.yml'
    # Don't run on Markdown changes
    - '!**.md'
    branches: [ master ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-testing-2022
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v1
      - name: Install dependencies 📦
        #Using npm ci is generally faster than running npm install
        run: |
          ls -a
          npm ci
      - name: Start the app
        run: |
          npm start &
          npx wait-on --timeout 60000
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          command-prefix: npx happo-e2e -- npx
        env:
          # Inject secrets to the build
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
      - name: Run visual tests 👁
        run: |
          ls -a
          npm run test:visual
        env:
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
